<?php

/**
 * Describes a harvest or use of a plant
 *
 * A class describing a harvest or use generated by a plant.
 *
 * @property	int	$id	The primary key.
 * @property	string	$name	The name/description of the harvest or use.
 */
class Harvest extends Eloquent
{
	public $timestamps = FALSE;

	protected $table = 'harvests';
	protected $hidden = array('pivot');
}
