name 'rails_vagrant'
maintainer 'Daniel Bingham'
maintainer_email 'dbingham@theroadgoeson.com'
license 'all_rights'
description 'Installs/Configures rails_vagrant'
long_description 'Installs/Configures rails_vagrant'
version '0.1.0'

depends 'apt', '~> 4.0.1'
depends 'mysql', '~> 7.0.0'
depends 'mysql2_chef_gem', '~> 1.1.0'
depends 'database', '~> 5.1.2'
depends 'nodejs', '~> 2.4.4'
